# Generated by Django 5.2.7 on 2025-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goods",
            options={"verbose_name": "商品", "verbose_name_plural": "商品"},
        ),
        migrations.RemoveField(
            model_name="goods",
            name="name",
        ),
        migrations.AddField(
            model_name="goods",
            name="category",
            field=models.CharField(
                default="通用分类", max_length=100, verbose_name="分类"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="title",
            field=models.CharField(
                default="默认商品名称", max_length=200, verbose_name="商品名称"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="价格"
            ),
        ),
    ]
