# Generated by Django 5.2.7 on 2025-10-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_goods_options_remove_goods_name_goods_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://via.placeholder.com/300x200?text=商品图片",
                null=True,
                verbose_name="图片链接",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="是否已售出"),
        ),
        migrations.AddField(
            model_name="goods",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="卖家",
            ),
        ),
    ]
