# Generated by Django 5.2.7 on 2025-10-31 07:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_goods_image_url_goods_is_sold_goods_seller"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goods",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
        migrations.RemoveField(
            model_name="goods",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="goods",
            name="title",
        ),
        migrations.AddField(
            model_name="goods",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "全新"),
                    ("like_new", "几乎全新"),
                    ("good", "良好"),
                    ("fair", "一般"),
                    ("needs_repair", "需维修"),
                ],
                default="good",
                max_length=20,
                verbose_name="商品状态",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="contact",
            field=models.CharField(
                default="未提供", max_length=50, verbose_name="联系方式"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goods/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                        message="只支持 JPG, JPEG, PNG, GIF, WebP 格式的图片",
                    )
                ],
                verbose_name="商品图片",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="所在位置"
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="name",
            field=models.CharField(
                default="默认商品名称", max_length=100, verbose_name="商品名称"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goods",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "电子产品"),
                    ("clothing", "服装鞋帽"),
                    ("books", "图书文具"),
                    ("sports", "运动户外"),
                    ("beauty", "美妆个护"),
                    ("home", "家居日用"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="商品分类",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="description",
            field=models.TextField(verbose_name="商品描述"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="price",
            field=models.FloatField(verbose_name="价格"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="卖家",
            ),
        ),
    ]
