# Generated by Django 5.2.7 on 2025-10-31 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_goods_options_remove_goods_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_goods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="购买者",
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="sold_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="售出时间"),
        ),
    ]
